services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "weatherdb"
      POSTGRES_USER: "postgrUser"
      POSTGRES_PASSWORD: "postgrPass"
