services:
  redis:
    container_name: redis
    image: "redis:latest"
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - app-redis-network

  postgres:
    container_name: postgres
    image: "postgres:16"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$USER
      - POSTGRES_PASSWORD=$PASSWORD
      - POSTGRES_DB=$DATABASE
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-db-network

  weatherapp:
    container_name: weatherapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$DATABASE
      - SPRING_DATASOURCE_USER=$USER
      - SPRING_DATASOURCE_PASSWORD=$PASSWORD
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - app-redis-network
      - app-db-network
      - app-nginx-network
    depends_on:
      - postgres
      - redis

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    networks:
      - app-nginx-network
    depends_on:
      - weatherapp


volumes:
  db:
  redis:

networks:
  app-redis-network:
  app-db-network:
  app-nginx-network:

